 insert all
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (1, 'Gorczany, Kovacek and Sanford', '33478 Schmedeman Alley', 'Wilkes Barre', 'Pennsylvania', '18706', 'tourism', 334511);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (2, 'Barton, Schowalter and Abbott', '97 Hoffman Park', 'Washington', 'District of Columbia', '20099', 'technology', 423430);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (3, 'Huel, Hauck and Baumbach', '1107 Granby Street', 'Cincinnati', 'Ohio', '45243', 'oil and mining', 511210);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (4, 'Emmerich-Kuhic', '5511 Melrose Avenue', 'Camden', 'New Jersey', '08104', 'oil and mining', 514210);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (5, 'Stiedemann-Keeling', '85721 Graceland Center', 'San Jose', 'California', '95160', 'service', 334112);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (6, 'Bergnaum, Kunde and Daniel', '3847 Jenifer Road', 'Largo', 'Florida', '34643', 'technology', 421430);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (7, 'Jerde, Grant and Weber', '559 Monument Terrace', 'Houston', 'Texas', '77218', 'tourism', 443120);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (8, 'Spencer, Morar and Schoen', '679 Garrison Road', 'Reston', 'Virginia', '22096', 'technology', 334511);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (9, 'Schmitt Inc', '9011 Transport Junction', 'Erie', 'Pennsylvania', '16505', 'oil and mining', 519130);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (10, 'Grant, Rau and Howe', '913 Sheridan Crossing', 'Virginia Beach', 'Virginia', '23471', 'service', 334119);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (11, 'Muller, Walsh and Rodriguez', '43865 Del Sol Trail', 'Oklahoma City', 'Oklahoma', '73190', 'tourism', 333295);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (12, 'Koelpin, Thiel and Heidenreich', '7 Eastlawn Drive', 'Provo', 'Utah', '84605', 'entertainment', 334111);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (13, 'Krajcik-Metz', '5324 Forest Run Point', 'Jacksonville', 'Florida', '32209', 'tourism', 541710);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (14, 'Koepp, Wilkinson and Spinka', '761 Arrowood Court', 'Houston', 'Texas', '77293', 'tourism', 541512);
 into Company (comp_id, c_name, street, city, st, zip_code, primary_sector, NAICS_code) values (15, 'Daugherty Group', '7 Lyons Place', 'Winston Salem', 'North Carolina', '27116', 'education', 334113);

  insert all
 into company_specialty (comp_id, specialty_name) values (3, 'IT consulting');
 into company_specialty (comp_id, specialty_name) values (1, 'logistics service');
 into company_specialty (comp_id, specialty_name) values (11, 'software');
 into company_specialty (comp_id, specialty_name) values (14, 'construction');
 into company_specialty (comp_id, specialty_name) values (3, 'software');
 into company_specialty (comp_id, specialty_name) values (7, 'electronics');
 into company_specialty (comp_id, specialty_name) values (8, 'IT consulting');
 into company_specialty (comp_id, specialty_name) values (13, 'transportation');
 into company_specialty (comp_id, specialty_name) values (6, 'IT consulting');
 into company_specialty (comp_id, specialty_name) values (12, 'computer hardware');

  insert all
 into core (cate_code, k_code) values (7, '15-1133');
 into core (cate_code, k_code) values (5, '15-1121');
 into core (cate_code, k_code) values (3, '15-1100');
 into core (cate_code, k_code) values (1, '15-1131');
 into core (cate_code, k_code) values (8, '15-1141');
 into core (cate_code, k_code) values (4, '15-1114');
 into core (cate_code, k_code) values (1, '15-1133');
 into core (cate_code, k_code) values (3, '15-1115');
 into core (cate_code, k_code) values (9, '15-1115');
 into core (cate_code, k_code) values (8, '15-1142');
 into core (cate_code, k_code) values (9, '15-1132');
 into core (cate_code, k_code) values (2, '15-1133');

  insert all
 into Course (course_id, title, lvl, credits) values (1, 'Introduction to Software Engineering', 3000, 3);
 into Course (course_id, title, lvl, credits) values (2, 'Introduction to Information Systems', 3000, 3);
 into Course (course_id, title, lvl, credits) values (3, 'Discrete Math', 3000, 3);
 into Course (course_id, title, lvl, credits) values (4, 'Algorithms', 3000, 3);
 into Course (course_id, title, lvl, credits) values (5, 'Data Structures', 2000, 4);
 into Course (course_id, title, lvl, credits) values (6, 'Programming Languages', 3000, 3);
 into Course (course_id, title, lvl, credits) values (7, 'Networking', 3000, 3);
 into Course (course_id, title, lvl, credits) values (8, 'Operating Systems', 4000, 3);
 into Course (course_id, title, lvl, credits) values (9, 'Databases', 4000, 3);
 into Course (course_id, title, lvl, credits) values (10, 'Computer Systems', 4000, 3);
 into Course (course_id, title, lvl, credits) values (11, 'AI', 4000, 3);
 into Course (course_id, title, lvl, credits) values (12, 'Information Security', 3000, 3);
 into Course (course_id, title, lvl, credits) values (13, 'Web Development', 4000, 3);
 into Course (course_id, title, lvl, credits) values (14, 'App Development', 3000, 4);
 into Course (course_id, title, lvl, credits) values (15, 'Reverse Engineering', 3000, 3);
 into Course (course_id, title, lvl, credits) values (16, 'Java I', 3000, 3);
 into Course (course_id, title, lvl, credits) values (17, 'Java II', 3000, 4);

  insert all
 into course_skill (course_id, k_code) values (17, '15-1117');
 into course_skill (course_id, k_code) values (10, '15-1121');
 into course_skill (course_id, k_code) values (17, '15-1116');
 into course_skill (course_id, k_code) values (7, '15-1143');
 into course_skill (course_id, k_code) values (13, '15-1143');
 into course_skill (course_id, k_code) values (7, '15-1114');
 into course_skill (course_id, k_code) values (4, '15-1133');
 into course_skill (course_id, k_code) values (13, '15-1117');
 into course_skill (course_id, k_code) values (5, '15-1122');
 into course_skill (course_id, k_code) values (5, '15-1113');
 into course_skill (course_id, k_code) values (6, '15-1117');
 into course_skill (course_id, k_code) values (3, '15-1143');
 into course_skill (course_id, k_code) values (3, '15-1100');
 into course_skill (course_id, k_code) values (16, '15-1116');
 into course_skill (course_id, k_code) values (11, '15-1113');

  insert all
 into has_job (job_id, person_id, start_date, end_date) values (8, 15, to_date('2012-11-28', 'YYYY-MM-DD'), to_date('2016-08-23', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (12, 3, to_date('2012-09-02', 'YYYY-MM-DD'), to_date('2017-04-17', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (2, 13, to_date('2011-03-03', 'YYYY-MM-DD'), to_date('2016-06-16', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (3, 15, to_date('2011-12-19', 'YYYY-MM-DD'), to_date('2016-04-27', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (11, 26, to_date('2011-08-20', 'YYYY-MM-DD'), to_date('2016-05-22', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (23, 4, to_date('2016-01-22', 'YYYY-MM-DD'), to_date('2016-07-19', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (2, 9, to_date('2011-02-03', 'YYYY-MM-DD'), to_date('2016-06-22', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (29, 1, to_date('2013-12-20', 'YYYY-MM-DD'), to_date('2016-11-21', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (14, 29, to_date('2012-10-05', 'YYYY-MM-DD'), to_date('2016-08-06', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (29, 12, to_date('2012-09-05', 'YYYY-MM-DD'), to_date('2016-10-26', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (19, 19, to_date('2015-07-26', 'YYYY-MM-DD'), to_date('2017-03-29', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (10, 20, to_date('2015-11-10', 'YYYY-MM-DD'), to_date('2016-07-19', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (22, 8, to_date('2012-12-15', 'YYYY-MM-DD'), to_date('2017-03-09', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (17, 4, to_date('2012-10-12', 'YYYY-MM-DD'), to_date('2016-11-19', 'YYYY-MM-DD'));
 into has_job (job_id, person_id, start_date, end_date) values (12, 12, to_date('2016-01-26', 'YYYY-MM-DD'), to_date('2017-03-05', 'YYYY-MM-DD'));

  insert all
 into has_skill (person_id, k_code) values (18, '15-1133');
 into has_skill (person_id, k_code) values (19, '15-1143');
 into has_skill (person_id, k_code) values (11, '15-1133');
 into has_skill (person_id, k_code) values (14, '15-1121');
 into has_skill (person_id, k_code) values (4, '15-1134');
 into has_skill (person_id, k_code) values (23, '15-1117');
 into has_skill (person_id, k_code) values (30, '15-1100');
 into has_skill (person_id, k_code) values (2, '15-1132');
 into has_skill (person_id, k_code) values (18, '15-1142');
 into has_skill (person_id, k_code) values (22, '15-1143');
 into has_skill (person_id, k_code) values (26, '15-1143');
 into has_skill (person_id, k_code) values (26, '15-1122');
 into has_skill (person_id, k_code) values (12, '15-1141');
 into has_skill (person_id, k_code) values (15, '15-1142');
 into has_skill (person_id, k_code) values (1, '15-1142');
 into has_skill (person_id, k_code) values (10, '15-1134');
 into has_skill (person_id, k_code) values (29, '15-1133');
 into has_skill (person_id, k_code) values (4, '15-1100');
 into has_skill (person_id, k_code) values (9, '15-1143');
 into has_skill (person_id, k_code) values (19, '15-1122');
 into has_skill (person_id, k_code) values (25, '15-1113');
 into has_skill (person_id, k_code) values (26, '15-1100');
 into has_skill (person_id, k_code) values (11, '15-1116');
 into has_skill (person_id, k_code) values (9, '15-1122');
 into has_skill (person_id, k_code) values (21, '15-1121');
 into has_skill (person_id, k_code) values (2, '15-1134');
 into has_skill (person_id, k_code) values (20, '15-1114');
 into has_skill (person_id, k_code) values (8, '15-1114');
 into has_skill (person_id, k_code) values (17, '15-1132');
 into has_skill (person_id, k_code) values (17, '15-1100');
 into has_skill (person_id, k_code) values (22, '15-1131');
 into has_skill (person_id, k_code) values (17, '15-1143');
 into has_skill (person_id, k_code) values (29, '15-1142');
 into has_skill (person_id, k_code) values (30, '15-1113');
 into has_skill (person_id, k_code) values (3, '15-1114');
 into has_skill (person_id, k_code) values (25, '15-1115');
 into has_skill (person_id, k_code) values (15, '15-1141');
 into has_skill (person_id, k_code) values (2, '15-1131');
 into has_skill (person_id, k_code) values (6, '15-1114');
 into has_skill (person_id, k_code) values (10, '15-1122');
 into has_skill (person_id, k_code) values (20, '15-1113');
 into has_skill (person_id, k_code) values (20, '15-1132');
 into has_skill (person_id, k_code) values (30, '15-1133');
 into has_skill (person_id, k_code) values (11, '15-1113');
 into has_skill (person_id, k_code) values (30, '15-1115');
 into has_skill (person_id, k_code) values (12, '15-1133');
 into has_skill (person_id, k_code) values (4, '15-1121');
 into has_skill (person_id, k_code) values (20, '15-1121');
 into has_skill (person_id, k_code) values (25, '15-1143');

  insert all
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (1, '$77.03', 'Salary', 1, 'Full-Time', 6);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (2, '$36.84', 'Hourly', 8, 'Part-Time', 9);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (3, '$48.20', 'Hourly', 9, 'Full-Time', 8);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (4, '$69.16', 'Salary', 1, 'Part-Time', 1);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (5, '$57.40', 'Hourly', 6, 'Full-Time', 7);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (6, '$62.32', 'Hourly', 4, 'Full-Time', 9);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (7, '$73.99', 'Hourly', 7, 'Full-Time', 5);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (8, '$68.86', 'Salary', 5, 'Part-Time', 6);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (9, '$54.92', 'Hourly', 7, 'Part-Time', 8);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (10, '$38.17', 'Salary', 4, 'Part-Time', 6);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (11, '$81.36', 'Salary', 6, 'Part-Time', 8);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (12, '$62.45', 'Salary', 4, 'Part-Time', 2);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (13, '$62.03', 'Hourly', 6, 'Part-Time', 6);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (14, '$87.15', 'Salary', 9, 'Full-Time', 10);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (15, '$57.94', 'Hourly', 9, 'Part-Time', 10);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (16, '$66.83', 'Hourly', 4, 'Part-Time', 10);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (17, '$61.45', 'Hourly', 4, 'Part-Time', 4);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (18, '$76.25', 'Hourly', 9, 'Full-Time', 9);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (19, '$75.68', 'Hourly', 3, 'Part-Time', 4);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (20, '$40.69', 'Salary', 8, 'Full-Time', 8);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (21, '$37.64', 'Salary', 9, 'Part-Time', 8);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (22, '$50.30', 'Salary', 1, 'Part-Time', 5);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (23, '$52.42', 'Hourly', 2, 'Full-Time', 5);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (24, '$62.76', 'Hourly', 8, 'Full-Time', 6);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (25, '$44.15', 'Salary', 7, 'Full-Time', 3);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (26, '$39.40', 'Salary', 9, 'Full-Time', 6);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (27, '$65.59', 'Hourly', 3, 'Full-Time', 7);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (28, '$53.71', 'Salary', 7, 'Full-Time', 2);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (29, '$74.29', 'Hourly', 5, 'Part-Time', 4);
 into Job (job_id, pay_rate, pay_type, comp_id, emp_mode, cate_code) values (30, '$44.85', 'Salary', 5, 'Part-Time', 4);

  insert all
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (1, '$42897.96', '$69053.79', 'Data Coordiator', 1, 'Software Developers/Applications');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (2, '$44096.99', '$83940.98', 'Social Worker', 2, 'Software Developers/Systems Software');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (3, '$41904.27', '$74709.51', 'Analog Circuit Design manager', 3, 'Software Developers/Systems Software');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (4, '$39882.85', '$83585.73', 'Marketing Manager', 4, 'Computer Systems Analysts');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (5, '$36471.93', '$80394.40', 'Help Desk Operator', 5, 'Computer Occupations/Other');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (6, '$41467.37', '$73862.19', 'Project Manager', 6, 'Software Developers/Applications');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (7, '$44079.23', '$83743.47', 'Marketing Assistant', 7, 'Computer Systems Analysts');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (8, '$42523.87', '$80954.14', 'Tax Accountant', 8, 'Computer Systems Analysts');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (9, '$34790.09', '$76819.74', 'Quality Control Specialist', 9, 'Software Developers/Systems Software');
 into Job_category (cate_code, pay_range_low, pay_range_high, title, parent_cate, soc) values (10, '$39202.41', '$74814.99', 'Media Manager I', 10, 'Software Developers/Systems Software');

  insert all
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1100', 'Bash', 'advanced', 'Software Developer');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1121', 'Cacti', 'beginner', 'QA Tester');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1122', 'ASP', 'medium', 'Database Administrator');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1131', 'Bash', 'beginner', 'Database Administrator');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1132', 'Adobe Photoshop', 'beginner', 'Systems Engineer');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1133', 'AngularJS', 'advanced', 'Network Administrator');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1134', 'AngularJS', 'advanced', 'Business Intelligence Analyst');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1141', '.NET Programming', 'beginner', 'QA Tester');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1142', 'Adobe Indesign', 'beginner', 'System Administrator');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1143', 'Cacti', 'beginner', 'Systems Analyst');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1113', 'Backbone.js', 'medium', 'Web Developer');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1114', 'Android Software Development Kit (SDK)', 'advanced', 'Web Developer');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1115', 'C++', 'advanced', 'QA Tester');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1116', 'Adobe Indesign', 'medium', 'Systems Engineer');
 into Knowledge_Skill (k_code, title, lvl, k_type) values ('15-1117', 'Accounting Software', 'advanced', 'Software Developer');

  insert all
 into NAICS (NAICS_code, title) values (333295, 'Semiconductor machinery mfg');
 into NAICS (NAICS_code, title) values (333315, 'Photographic and photocopying equipment manufacturing');
 into NAICS (NAICS_code, title) values (334111, 'Electronic computer mfg');
 into NAICS (NAICS_code, title) values (334112, 'Computer storage device mfg');
 into NAICS (NAICS_code, title) values (334113, 'Computer terminal mfg');
 into NAICS (NAICS_code, title) values (334119, 'Other computer peripheral equipment mfg');
 into NAICS (NAICS_code, title) values (334210, 'Telephone apparatus manufacturing');
 into NAICS (NAICS_code, title) values (334220, 'Broadcast and wireless communications equipment');
 into NAICS (NAICS_code, title) values (334413, 'Semiconductor and related device manufacturing');
 into NAICS (NAICS_code, title) values (334511, 'Search/detection/navigation/guidance/aeronautical/nautical system/instrument manufacturing');
 into NAICS (NAICS_code, title) values (421430, 'Computer & peripheral equip & software whsle');
 into NAICS (NAICS_code, title) values (421690, 'Other electronic parts & equipment whsle');
 into NAICS (NAICS_code, title) values (423430, 'Computer and computer peripheral equipment and software merchant wholesalers');
 into NAICS (NAICS_code, title) values (423690, 'Other electronic parts and equipment merchant wholesalers');
 into NAICS (NAICS_code, title) values (443120, 'Computer and software stores');
 into NAICS (NAICS_code, title) values (511140, 'Database and directory publishers');
 into NAICS (NAICS_code, title) values (511210, 'Software publishers');
 into NAICS (NAICS_code, title) values (514210, 'Data processing services');
 into NAICS (NAICS_code, title) values (518210, 'Data processing/hosting/related services');
 into NAICS (NAICS_code, title) values (519130, 'Internet publishing and broadcasting and web search portals');
 into NAICS (NAICS_code, title) values (541330, 'Engineering services');
 into NAICS (NAICS_code, title) values (541511, 'Custom computer programming services');
 into NAICS (NAICS_code, title) values (541512, 'Computer systems design services');
 into NAICS (NAICS_code, title) values (541513, 'Computer facilities management services');
 into NAICS (NAICS_code, title) values (541519, 'Other computer related services');
 into NAICS (NAICS_code, title) values (541710, 'R&D in physical/engineering & life sciences');
 into NAICS (NAICS_code, title) values (541711, 'Research and development in biotechnology');
 into NAICS (NAICS_code, title) values (541712, 'Research and development in the physical/engineering/life sciences (except biotechnology)');

  insert all
 into NWCET (skill_name) values ('Database Development');
 into NWCET (skill_name) values ('Database Administration');
 into NWCET (skill_name) values ('Digital Media');
 into NWCET (skill_name) values ('Enterprise Systems Analysis and Integration');
 into NWCET (skill_name) values ('Network Design and Administration');
 into NWCET (skill_name) values ('Programming');
 into NWCET (skill_name) values ('Software Engineering');
 into NWCET (skill_name) values ('Technical Support');
 into NWCET (skill_name) values ('Technical Writing');
 into NWCET (skill_name) values ('Web Development');
 into NWCET (skill_name) values ('Web Administration');

  insert all
 into NWCET_skill (k_code, skill_name) values ('15-1116', 'Enterprise Systems Analysis and Integration');
 into NWCET_skill (k_code, skill_name) values ('15-1115', 'Network Design and Administration');
 into NWCET_skill (k_code, skill_name) values ('15-1121', 'Web Administration');
 into NWCET_skill (k_code, skill_name) values ('15-1121', 'Software Engineering');
 into NWCET_skill (k_code, skill_name) values ('15-1132', 'Database Development');
 into NWCET_skill (k_code, skill_name) values ('15-1143', 'Network Design and Administration');
 into NWCET_skill (k_code, skill_name) values ('15-1122', 'Technical Writing');
 into NWCET_skill (k_code, skill_name) values ('15-1133', 'Programming');
 into NWCET_skill (k_code, skill_name) values ('15-1134', 'Database Development');
 into NWCET_skill (k_code, skill_name) values ('15-1131', 'Database Development');
 into NWCET_skill (k_code, skill_name) values ('15-1116', 'Digital Media');
 into NWCET_skill (k_code, skill_name) values ('15-1142', 'Web Development');
 into NWCET_skill (k_code, skill_name) values ('15-1116', 'Programming');
 into NWCET_skill (k_code, skill_name) values ('15-1141', 'Web Development');
 into NWCET_skill (k_code, skill_name) values ('15-1132', 'Programming');

  insert all
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (1, 'Raynell Faill', '7 Pond Junction', 'Houston', 'TX', '77288', 'rfaill0@fc2.com', 'M', '62-(560)968-9742');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (2, 'Carlotta Sawell', '74766 Fairview Circle', 'Muskegon', 'MI', '49444', 'csawell1@tinypic.com', 'M', '51-(633)416-1142');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (3, 'Jasmina Laneham', '7262 David Parkway', 'Greensboro', 'NC', '27404', 'jlaneham2@youku.com', 'F', '46-(180)551-8938');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (4, 'Rodrick Wicklen', '38990 Autumn Leaf Avenue', 'Salt Lake City', 'UT', '84135', 'rwicklen3@house.gov', 'F', '351-(659)404-9987');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (5, 'Gerhard Albery', '1613 Lotheville Circle', 'Chattanooga', 'TN', '37416', 'galbery4@de.vu', 'M', '55-(846)213-1822');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (6, 'Tracey Kopfen', '0 Hoard Parkway', 'North Little Rock', 'AR', '72199', 'tkopfen5@msn.com', 'F', '86-(852)204-9227');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (7, 'Tate Treppas', '563 Mallory Plaza', 'Vancouver', 'WA', '98687', 'ttreppas6@cpanel.net', 'M', '84-(481)946-0362');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (8, 'Sibbie Bursell', '55 Anhalt Center', 'Toledo', 'OH', '43610', 'sbursell7@unicef.org', 'M', '7-(245)934-0611');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (9, 'Erna Pomfret', '83798 Blaine Alley', 'Saint Louis', 'MO', '63158', 'epomfret8@cmu.edu', 'F', '81-(909)964-2875');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (10, 'Alyosha Gillard', '83 Springview Crossing', 'Knoxville', 'TN', '37919', 'agillard9@behance.net', 'F', '63-(219)700-3084');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (11, 'Tirrell Egell', '5264 Birchwood Pass', 'New York City', 'NY', '10275', 'tegella@cmu.edu', 'M', '55-(846)213-1822');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (12, 'Arlinda Panons', '0 New Castle Parkway', 'Chicago', 'IL', '60669', 'apanonsb@sitemeter.com', 'M', '81-(158)903-8913');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (13, 'Belia Smowton', '02 South Park', 'Shreveport', 'LA', '71151', 'bsmowtonc@webeden.co.uk', 'M', '86-(447)799-8262');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (14, 'Barry Crennell', '712 Dryden Point', 'Spokane', 'WA', '99210', 'bcrennelld@flavors.me', 'M', '81-(158)903-8913');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (15, 'Sissie Baddiley', '587 Shoshone Plaza', 'Washington', 'DC', '20404', 'sbaddileye@opensource.org', 'M', '355-(843)277-4181');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (16, 'Eula Cardnell', '8134 Esch Drive', 'Chico', 'CA', '95973', 'ecardnellf@ucla.edu', 'F', '81-(158)903-8913');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (17, 'Sissy Eberle', '4 Raven Hill', 'New York City', 'NY', '10280', 'seberleg@archive.org', 'F', '251-(743)358-9267');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (18, 'Coleman O''Lennachain', '101 Merrick Drive', 'Phoenix', 'AZ', '85015', 'colennachainh@ucoz.ru', 'M', '62-(817)709-2139');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (19, 'Park Deverick', '920 Dixon Place', 'Honolulu', 'HI', '96825', 'pdevericki@joomla.org', 'F', '45-(511)792-6876');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (20, 'Pam Eggar', '1 Westridge Way', 'Manassas', 'VA', '22111', 'peggarj@hostgator.com', 'F', '86-(447)799-8262');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (21, 'Maximilian Riccardo', '96715 Sloan Terrace', 'Sunnyvale', 'CA', '94089', 'mriccardok@fema.gov', 'M', '63-(219)700-3084');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (22, 'Sallee Lindblad', '08097 Reinke Court', 'Paterson', 'NJ', '07544', 'slindbladl@umn.edu', 'M', '251-(743)358-9267');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (23, 'Gratia Skirlin', '88 Stoughton Parkway', 'El Paso', 'TX', '88574', 'gskirlinm@e-recht24.de', 'F', '84-(978)152-9282');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (24, 'Brantley Senyard', '0 Forest Center', 'Honolulu', 'HI', '96810', 'bsenyardn@printfriendly.com', 'F', '7-(356)248-1692');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (25, 'Nedda Feather', '633 Clemons Circle', 'Brea', 'CA', '92822', 'nfeathero@bandcamp.com', 'F', '351-(664)670-4210');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (26, 'Lori Cutler', '1770 Warbler Plaza', 'Saint Cloud', 'MN', '56398', 'lcutlerp@usa.gov', 'F', '380-(922)843-6861');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (27, 'Marisa Smartman', '9 Basil Place', 'Boise', 'ID', '83705', 'msmartmanq@plala.or.jp', 'F', '84-(481)946-0362');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (28, 'Gloriane Haddrell', '2 Vidon Court', 'San Jose', 'CA', '95150', 'ghaddrellr@dailymotion.com', 'M', '81-(909)964-2875');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (29, 'Trev Inglesent', '06 Farragut Hill', 'Huntington', 'WV', '25711', 'tinglesents@sfgate.com', 'M', '55-(152)454-5044');
 into Person (person_id, p_name, address, city, st, zip_code, email, gender, phone) values (30, 'Allin Grigolli', '9205 Park Meadow Drive', 'New Orleans', 'LA', '70165', 'agrigollit@princeton.edu', 'F', '62-(817)709-2139');

  insert all
 into person_phone (person_id, p_number, p_type) values (15, '86-(517)494-1177', 'Mobile');
 into person_phone (person_id, p_number, p_type) values (29, '62-(480)797-9066', 'Home');
 into person_phone (person_id, p_number, p_type) values (7, '66-(214)319-8147', 'Home');
 into person_phone (person_id, p_number, p_type) values (13, '63-(689)510-4525', 'Home');
 into person_phone (person_id, p_number, p_type) values (23, '7-(117)944-7630', 'Home');
 into person_phone (person_id, p_number, p_type) values (26, '66-(460)384-4813', 'Work');
 into person_phone (person_id, p_number, p_type) values (18, '54-(714)504-3342', 'Home');
 into person_phone (person_id, p_number, p_type) values (3, '30-(820)481-4487', 'Mobile');
 into person_phone (person_id, p_number, p_type) values (21, '598-(287)793-5986', 'Home');
 into person_phone (person_id, p_number, p_type) values (9, '420-(310)465-5422', 'Home');
 into person_phone (person_id, p_number, p_type) values (24, '51-(769)653-5042', 'Home');
 into person_phone (person_id, p_number, p_type) values (22, '62-(975)426-7498', 'Work');
 into person_phone (person_id, p_number, p_type) values (4, '7-(465)554-1409', 'Work');
 into person_phone (person_id, p_number, p_type) values (22, '55-(422)295-7048', 'Work');
 into person_phone (person_id, p_number, p_type) values (13, '86-(122)531-8951', 'Work');

  insert all
 into Phone (p_number, p_type) values ('86-(517)494-1177', 'Mobile');
 into Phone (p_number, p_type) values ('62-(480)797-9066', 'Home');
 into Phone (p_number, p_type) values ('66-(214)319-8147', 'Home');
 into Phone (p_number, p_type) values ('63-(689)510-4525', 'Home');
 into Phone (p_number, p_type) values ('7-(117)944-7630', 'Home');
 into Phone (p_number, p_type) values ('66-(460)384-4813', 'Work');
 into Phone (p_number, p_type) values ('54-(714)504-3342', 'Home');
 into Phone (p_number, p_type) values ('30-(820)481-4487', 'Mobile');
 into Phone (p_number, p_type) values ('598-(287)793-5986', 'Home');
 into Phone (p_number, p_type) values ('420-(310)465-5422', 'Home');
 into Phone (p_number, p_type) values ('51-(769)653-5042', 'Home');
 into Phone (p_number, p_type) values ('62-(975)426-7498', 'Work');
 into Phone (p_number, p_type) values ('7-(465)554-1409', 'Work');
 into Phone (p_number, p_type) values ('55-(422)295-7048', 'Work');
 into Phone (p_number, p_type) values ('86-(122)531-8951', 'Work');
 into Phone (p_number, p_type) values ('86-(911)115-0035', 'Work');
 into Phone (p_number, p_type) values ('86-(466)790-6197', 'Work');
 into Phone (p_number, p_type) values ('1-(669)160-7696', 'Home');
 into Phone (p_number, p_type) values ('62-(304)124-2068', 'Work');
 into Phone (p_number, p_type) values ('380-(333)418-4517', 'Mobile');
 into Phone (p_number, p_type) values ('251-(667)158-0454','Mobile');
 into Phone (p_number, p_type) values ('371-(159)758-6237','Work');
 into Phone (p_number, p_type) values ('63-(587)457-2249','Home');
 into Phone (p_number, p_type) values ('51-(630)809-2746','Mobile');
 into Phone (p_number, p_type) values ('255-(580)415-0058','Mobile');
 into Phone (p_number, p_type) values ('62-(955)280-1936','Work');
 into Phone (p_number, p_type) values ('351-(134)975-8381','Work');
 into Phone (p_number, p_type) values ('66-(824)108-5125','Home');
 into Phone (p_number, p_type) values ('7-(199)537-4502','Work');
 into Phone (p_number, p_type) values ('251-(741)730-7059','Work');
 into Phone (p_number, p_type) values ('46-(576)523-0609','Work');
 into Phone (p_number, p_type) values ('86-(278)278-0816','Mobile');

  insert all
 into pre_req (prereq_id, course_id) values (1, 17);
 into pre_req (prereq_id, course_id) values (2, 4);
 into pre_req (prereq_id, course_id) values (3, 6);
 into pre_req (prereq_id, course_id) values (4, 13);
 into pre_req (prereq_id, course_id) values (5, 3);
 into pre_req (prereq_id, course_id) values (6, 4);
 into pre_req (prereq_id, course_id) values (7, 11);
 into pre_req (prereq_id, course_id) values (8, 2);
 into pre_req (prereq_id, course_id) values (9, 1);
 into pre_req (prereq_id, course_id) values (10, 2);

  insert all
 into preferred (job_id, k_code) values (12, '15-1141');
 into preferred (job_id, k_code) values (3, '15-1141');
 into preferred (job_id, k_code) values (29, '15-1143');
 into preferred (job_id, k_code) values (7, '15-1143');
 into preferred (job_id, k_code) values (12, '15-1134');
 into preferred (job_id, k_code) values (12, '15-1121');
 into preferred (job_id, k_code) values (19, '15-1117');
 into preferred (job_id, k_code) values (26, '15-1133');
 into preferred (job_id, k_code) values (13, '15-1143');
 into preferred (job_id, k_code) values (4, '15-1117');
 into preferred (job_id, k_code) values (22, '15-1134');
 into preferred (job_id, k_code) values (23, '15-1116');
 into preferred (job_id, k_code) values (4, '15-1122');
 into preferred (job_id, k_code) values (19, '15-1113');
 into preferred (job_id, k_code) values (19, '15-1134');
 into preferred (job_id, k_code) values (23, '15-1142');
 into preferred (job_id, k_code) values (17, '15-1115');
 into preferred (job_id, k_code) values (24, '15-1134');
 into preferred (job_id, k_code) values (4, '15-1133');
 into preferred (job_id, k_code) values (15, '15-1143');
 into preferred (job_id, k_code) values (20, '15-1143');
 into preferred (job_id, k_code) values (17, '15-1116');
 into preferred (job_id, k_code) values (21, '15-1132');
 into preferred (job_id, k_code) values (13, '15-1133');
 into preferred (job_id, k_code) values (2, '15-1115');
 into preferred (job_id, k_code) values (6, '15-1141');
 into preferred (job_id, k_code) values (15, '15-1141');
 into preferred (job_id, k_code) values (9, '15-1142');
 into preferred (job_id, k_code) values (10, '15-1131');
 into preferred (job_id, k_code) values (15, '15-1113');

  insert all
 into required (job_id, k_code) values (17, '15-1131');
 into required (job_id, k_code) values (12, '15-1122');
 into required (job_id, k_code) values (7, '15-1142');
 into required (job_id, k_code) values (9, '15-1117');
 into required (job_id, k_code) values (21, '15-1117');
 into required (job_id, k_code) values (13, '15-1141');
 into required (job_id, k_code) values (12, '15-1116');
 into required (job_id, k_code) values (20, '15-1113');
 into required (job_id, k_code) values (30, '15-1113');
 into required (job_id, k_code) values (16, '15-1115');
 into required (job_id, k_code) values (16, '15-1117');
 into required (job_id, k_code) values (18, '15-1131');
 into required (job_id, k_code) values (26, '15-1141');
 into required (job_id, k_code) values (1, '15-1131');
 into required (job_id, k_code) values (25, '15-1117');
 into required (job_id, k_code) values (3, '15-1143');
 into required (job_id, k_code) values (21, '15-1116');
 into required (job_id, k_code) values (26, '15-1115');
 into required (job_id, k_code) values (28, '15-1116');
 into required (job_id, k_code) values (6, '15-1115');
 into required (job_id, k_code) values (4, '15-1115');
 into required (job_id, k_code) values (7, '15-1141');
 into required (job_id, k_code) values (16, '15-1116');
 into required (job_id, k_code) values (26, '15-1100');
 into required (job_id, k_code) values (13, '15-1122');
 into required (job_id, k_code) values (20, '15-1132');
 into required (job_id, k_code) values (29, '15-1117');
 into required (job_id, k_code) values (8, '15-1134');
 into required (job_id, k_code) values (27, '15-1141');
 into required (job_id, k_code) values (19, '15-1115');

  insert all
into Section (sec_id, semester, yr, completion_date, course_id) values (1, 'Summer', 2012, to_date('2012-08-01', 'YYYY-MM-DD'), '$331.16', 2);
into Section (sec_id, semester, yr, completion_date, course_id) values (2, 'Spring', 2017, to_date('2017-05-01', 'YYYY-MM-DD'), '$221.26', 16);
into Section (sec_id, semester, yr, completion_date, course_id) values (3, 'Summer', 2011, to_date('2011-08-01', 'YYYY-MM-DD'), '$441.36', 8);
into Section (sec_id, semester, yr, completion_date, course_id) values (4, 'Spring', 2015, to_date('2015-05-01', 'YYYY-MM-DD'), '$551.46', 2);
into Section (sec_id, semester, yr, completion_date, course_id) values (5, 'Summer', 2011, to_date('2011-08-01', 'YYYY-MM-DD'), '222.55', 4);
into Section (sec_id, semester, yr, completion_date, course_id) values (6, 'Spring', 2017, to_date('2017-05-01', 'YYYY-MM-DD'), '$333.66', 8);
into Section (sec_id, semester, yr, completion_date, course_id) values (7, 'Spring', 2014, to_date('2014-05-01', 'YYYY-MM-DD'), '$444.76', 8);
into Section (sec_id, semester, yr, completion_date, course_id) values (8, 'Spring', 2014, to_date('2014-05-01', 'YYYY-MM-DD'), '$555.86', 13);
into Section (sec_id, semester, yr, completion_date, course_id) values (9, 'Fall', 2013, to_date('2013-12-15', 'YYYY-MM-DD'), '$321.96', 4);
into Section (sec_id, semester, yr, completion_date, course_id) values (10, 'Fall', 2014, to_date('2014-12-15', 'YYYY-MM-DD'), '$232.22', 6);
into Section (sec_id, semester, yr, completion_date, course_id) values (11, 'Spring', 2013, to_date('2013-05-01', 'YYYY-MM-DD'), '$431.33', 14);
into Section (sec_id, semester, yr, completion_date, course_id) values (12, 'Spring', 2015, to_date('2015-05-01', 'YYYY-MM-DD'), '$531.44', 9);
into Section (sec_id, semester, yr, completion_date, course_id) values (13, 'Spring', 2013, to_date('2013-05-01', 'YYYY-MM-DD'), '$541.55', 7);
into Section (sec_id, semester, yr, completion_date, course_id) values (14, 'Fall', 2009, to_date('2009-12-15', 'YYYY-MM-DD'), '$354.66', 14);
into Section (sec_id, semester, yr, completion_date, course_id) values (15, 'Summer', 2010, to_date('2010-08-01', 'YYYY-MM-DD'), '$422.77', 7);
into Section (sec_id, semester, yr, completion_date, course_id) values (16, 'Spring', 2009, to_date('2009-05-01', 'YYYY-MM-DD'), '$411.88', 11);
into Section (sec_id, semester, yr, completion_date, course_id) values (17, 'Spring', 2014, to_date('2014-05-01', 'YYYY-MM-DD'), '$290.99', 2);
into Section (sec_id, semester, yr, completion_date, course_id) values (18, 'Fall', 2009, to_date('2009-12-15', 'YYYY-MM-DD'), '$390.00', 11);
into Section (sec_id, semester, yr, completion_date, course_id) values (19, 'Spring', 2010, to_date('2010-05-01', 'YYYY-MM-DD'), '$490.11', 3);
into Section (sec_id, semester, yr, completion_date, course_id) values (20, 'Summer', 2011, to_date('2011-08-01', 'YYYY-MM-DD'), '$414.22', 13);

  insert all
 into SOC (major_soc, detail_soc) values ('15-1111', 'Computer and Information Research Scientists');
 into SOC (major_soc, detail_soc) values ('15-1121', 'Computer Systems Analysts');
 into SOC (major_soc, detail_soc) values ('15-1122', 'Information Security Analysts');
 into SOC (major_soc, detail_soc) values ('15-1131', 'Computer Programmers');
 into SOC (major_soc, detail_soc) values ('15-1132', 'Software Developers/Applications');
 into SOC (major_soc, detail_soc) values ('15-1133', 'Software Developers/Systems Software');
 into SOC (major_soc, detail_soc) values ('15-1134', 'Web Developers');
 into SOC (major_soc, detail_soc) values ('15-1141', 'Database Administrators');
 into SOC (major_soc, detail_soc) values ('15-1142', 'Network and Computer Systems Administrators');
 into SOC (major_soc, detail_soc) values ('15-1143', 'Computer Network Architects');
 into SOC (major_soc, detail_soc) values ('15-1151', 'Computer User Support Specialists');
 into SOC (major_soc, detail_soc) values ('15-1152', 'Computer Network Support Specialists');
 into SOC (major_soc, detail_soc) values ('15-1199', 'Computer Occupations/Other');

  insert all
 into Specialty (specialty_name) values ('construction');
 into Specialty (specialty_name) values ('logistics service');
 into Specialty (specialty_name) values ('computer hardware');
 into Specialty (specialty_name) values ('software');
 into Specialty (specialty_name) values ('electronics');
 into Specialty (specialty_name) values ('basic materials');
 into Specialty (specialty_name) values ('IT consulting');
 into Specialty (specialty_name) values ('transportation');

  insert all
 into takes (person_id, sec_id, semester, yr, grade) values (11, 10, 'Spring', 2009, 'A');
 into takes (person_id, sec_id, semester, yr, grade) values (6, 1, 'Spring', 2016, 'B');
 into takes (person_id, sec_id, semester, yr, grade) values (6, 15, 'Spring', 2012, 'D');
 into takes (person_id, sec_id, semester, yr, grade) values (10, 4, 'Summer', 2016, 'B');
 into takes (person_id, sec_id, semester, yr, grade) values (14, 10, 'Spring', 2009, 'A');
 into takes (person_id, sec_id, semester, yr, grade) values (9, 9, 'Spring', 2014, 'C');
 into takes (person_id, sec_id, semester, yr, grade) values (13, 10, 'Spring', 2009, 'C');
 into takes (person_id, sec_id, semester, yr, grade) values (20, 16, 'Summer', 2011, 'F');
 into takes (person_id, sec_id, semester, yr, grade) values (1, 17, 'Fall', 2009, 'C');
 into takes (person_id, sec_id, semester, yr, grade) values (30, 16, 'Summer', 2011, 'C');
 into takes (person_id, sec_id, semester, yr, grade) values (19, 5, 'Summer', 2013, 'A');
 into takes (person_id, sec_id, semester, yr, grade) values (2, 9, 'Spring', 2014, 'B');
 into takes (person_id, sec_id, semester, yr, grade) values (20, 10, 'Spring', 2009, 'A');
 into takes (person_id, sec_id, semester, yr, grade) values (7, 7, 'Spring', 2014, 'A');
 into takes (person_id, sec_id, semester, yr, grade) values (1, 9, 'Spring', 2014, 'B');
 into takes (person_id, sec_id, semester, yr, grade) values (28, 2, 'Spring', 2012, 'B');
 into takes (person_id, sec_id, semester, yr, grade) values (29, 2, 'Spring', 2012, 'B');
 into takes (person_id, sec_id, semester, yr, grade) values (18, 4, 'Summer', 2016, 'A');
 into takes (person_id, sec_id, semester, yr, grade) values (22, 5, 'Summer', 2013, 'C');
 into takes (person_id, sec_id, semester, yr, grade) values (7, 11, 'Fall', 2015, 'B');
